In [2]:
import numpy as np
np.random.seed(42)

# Problem 1: Tạo hai ma trận 3x3 với các phần tử integer ngẫu nhiên từ 1 - 10.

In [3]:
# Your code here

A = np.random.randint(0, 11, (3, 3))
B = np.random.randint(0, 11, (3, 3))

# Problem 2: Thực hiện phép cộng phần tử, nhân từng phần tử, tích vô hướng với hai ma trận vừa được tạo.


In [4]:
# Your code here

print(A+B)
print(A*B)
print(A.dot(B))

[[16 13 17]
 [11  7 13]
 [16  4 11]]
[[60 30 70]
 [28 12 42]
 [63  4 30]]
[[142  89 113]
 [128  94 107]
 [140 108 107]]


# Problem 3: VIết hàm nhận vào một mảng Numpy, sau đó trả về tổng tất cả các phần tử của chúng


In [7]:
# Your code here

def sum_elements(npArr):
    return np.sum(npArr)